# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-09-16 14:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=50)),
                ('position', models.CharField(choices=[(b'RB', b'RB'), (b'WR', b'WR'), (b'QB', b'QB'), (b'TE', b'TE'), (b'K', b'K')], max_length=10)),
                ('profile_url', models.CharField(max_length=250)),
                ('playerid', models.CharField(max_length=200)),
                ('avg_adp', models.DecimalField(decimal_places=15, max_digits=30, null=True)),
                ('std_dev', models.DecimalField(decimal_places=15, max_digits=30, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('year', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('abrv', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('number', models.SmallIntegerField()),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weeks', to='core.Season')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WeeklyStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('rushing_atts', models.SmallIntegerField(default=0)),
                ('rushing_yds', models.IntegerField(default=0)),
                ('rushing_tds', models.IntegerField(default=0)),
                ('passing_atts', models.SmallIntegerField(default=0)),
                ('passing_cmps', models.IntegerField(default=0)),
                ('passing_yds', models.IntegerField(default=0)),
                ('passing_tds', models.IntegerField(default=0)),
                ('passing_ints', models.SmallIntegerField(default=0)),
                ('receiving_rec', models.SmallIntegerField(default=0)),
                ('receiving_yds', models.IntegerField(default=0)),
                ('receiving_tds', models.IntegerField(default=0)),
                ('total_score', models.IntegerField(default=0)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_stats', to='core.Player')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Season')),
                ('week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_stats', to='core.Week')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='core.Team'),
        ),
    ]
