football:
  restart: always
  build: ./football
  expose:
    - "8000"
  links:
    - postgres:postgres
    - redis:redis
  volumes:
    - ./football:/usr/src/app
    - ./football/static:/usr/src/app/static
  env_file: .env
  command: /usr/local/bin/gunicorn football_tools.wsgi:application -w 2 -b :8000 --reload

nginx:
  restart: always
  build: ./nginx/
  ports:
    - "82:80"
  volumes:
    - /www/static
  volumes_from:
    - football
  links:
    - football:football

postgres:
  restart: always
  image: postgres:latest
  volumes_from:
    - data
  ports:
    - "5435:5432"

redis:
  restart: always
  image: redis:latest
  ports:
    - "6381:6381"

data:
  restart: always
  image: postgres:latest
  volumes:
    - /var/lib/postgresql
  command: "true"
